travis:
  secure:
    BINSTAR_TOKEN: rlVLEZjfmlDaPUV0t+62kkn1CcVZ191+TziojdglfMA5WZVFnX1woQqDR4mSPK7wukS3YMt5riEuIC42CiIjC1Lfil+0N3Nafbotnt7xslGoAg48md1kNgPQReUJlnT2cK/Uo2T0+VG0HGbyO5y7BqUy6eYkBFGFjVwy8slHmpmAVbqTcl/jhRUA6GLAtIq4PVEqA0mYaZZe9sW4YMpy/0iAbILaBPOQd13vii5YyOA7oHVbbgUtS2eUpsUzn0X6COtuKXNgggJndOgG5JB2BGbByk2pqpmld4HWYaDyjC5ZSi7GbXUwa4i+6i7CRFfsRrAr9Zrr4YMLoreiUkRgJP8dZy9t6yf4b0mX2brm6zsLETIlGwxqR+6YRQu1EAmIrCvhqdcZGTRrWPffSIUzZze9ixZWbzEUFtYqhw+yaSNpfkIevjYg+B5wxsWF0Ut3zd/K/Rj1RSwudE1SppbW/hvK1mIda8lpDPKzr9f7W63GYjNkEyo1TLxzVmUcfSUZVboim3Qag10U6R9SU2oCSqP3NtUKthCfKCEJ5thBiwvkgLlN/k9PxfrRw0mcpJTe3hrMHqkr6APBZce+Xvw2Kbl8Wy6DnJLZegPbP4qBqXFaJCRyfBIKd3Dk7JtI9pQRmln3K7kL2SzYfDslog6EEzYAGh4yqTw74CFtkcvS4IY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
